layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# projects:
#   sort_by: pushed
#   # sort_by options:
#   #   - pushed
#   #   - stars
#   limit: 9
#   exclude:
#     archived: false
#     forks: true
#     projects:
#     # - repo-name

social_media:
  orcid: 0000-0001-6256-888X
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: robert-forrest-phys
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
topics:
  - name: Scientific Computing
  #     web_url: https://github.com/topics/css
  #     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Research Automation

  - name: Machine Learning

  - name: Metallic Glasses
#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
background:
  - degree: PhD
    topic: Materials Science
    university: University of Cambridge
    start: 2019
    end: Present

  - degree: MPhil
    topic: Scientific Computing
    university: University of Cambridge
    start: 2018
    end: 2019
    grade: Distinction

  - degree: MPhys
    topic: Theoretical Physics
    university: University of York
    start: 2014
    end: 2018
    grade: First Class with Distinction

theme: jekyll-theme-minimal